service: notifications

provider:
  name: aws
  stage: dev
  runtime: nodejs4.3
  profile: solutioning
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: Allow
      Action:
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
      Resource:
        Fn::GetAtt: [SQSGeneralNotification, Arn]
    - Effect: Allow
      Action:
        - "sns:Publish"
      Resource: "*"

functions:
  agent:
    handler: agent.handler
  slack:
    handler: slack.handler
    events:
      - sns: ${opt:stage, self:provider.stage}-notifier

resources:
  Resources:
    SQSGeneralNotification:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${opt:stage, self:provider.stage}-GeneralNotifications
    SNSNotifyOfChange:
      Type: "AWS::SNS::Topic"
      Properties:
        DisplayName: "Notification of Change"
        TopicName: ${opt:stage, self:provider.stage}-NotifyOfChange